version: "3.9"

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    restart: always
    ports:
      - "11434:11434" 
    networks:
      - backend

  vuln-llm:
    build: .
    container_name: vuln-llm
    depends_on:
      - ollama
    ports:
      - "80:80"  
      - "8000:8000"
    environment:
      - OLLAMA_API_BASE=http://ollama:11434
    networks:
      - backend

networks:
  backend:
